### ISSUE TITLE
HAL comparison of TI chips CC2538 vs CC2630

### ISSUE THREAD

**Issue by ivankravets** [smartanthill/zepto-os#1]
TI released new series CC26xx of ultra-low power MCUs. Need to analyse a difference between these chips from programming point. We have TI DKs which are based on CC2538.

http://www.ti.com/product/cc2538
http://www.ti.com/product/cc2630
- [ ] Can we start work with CC2538 and switch to CC2630  in the future? 
- [ ] Is huge difference between CC2538 and CC2630 using TI `driverlibs`?

I propose to test "Blinky" example and compare both projects using TI Compose Studio.

**Comment by valeros** [comment]
I have looked on a both driverlib for this MCUs and want to say that these libraries are different, CC2630 uses newer version of driverlib (2.0). It has another structure, more peripheral modules (power control, crypto, random number generator, etc), some similar modules have different API (a different set of functions and their parameters), but some modules have the same API.
Also, CC26xx Firmware package already has the linker script file for compilation projects with gcc toolchain, but for cc2538 I've searched it over Internet.
