### ISSUE TITLE
do not use by-member syntax for structure declaration with initialization

### ISSUE THREAD

**Issue by divanchykhin** [smartanthill/zepto-os#19]
Currently found in sa_bodypart_list.c (and can potentially be at other places)
Example: 
smart_echo_plugin_config smart_echo_plugin_config_0={ .dummy=1 };
One of reasons: can cause compilation errors on compilers with C standard prior to C99

**Comment by ivankravets** [comment]
Resolved in https://github.com/smartanthill/smartanthill2_0/commit/43bd9112326adf20860608c472ab8aa11b499c66
